/**
 * Self-hosts the webfonts so the page makes zero third-party requests on load.
 * Google Fonts costs two extra DNS+TLS round trips before any text can paint,
 * which is real money on paid traffic.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Downloads the woff2 files into assets/fonts/ and writes assets/css/fonts.css
 * with the @font-face rules rewritten to local paths.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = resolve(ROOT, 'assets/fonts');

// A modern UA is required, or Google serves legacy ttf instead of woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'Comfortaa', css: 'family=Comfortaa:wght@300..700' },
  { name: 'Nunito',    css: 'family=Nunito:ital,wght@0,200..1000;1,200..1000' },
];

// Only Latin is needed; Cyrillic/Greek/Vietnamese would triple the payload.
const KEEP_SUBSETS = ['latin', 'latin-ext'];

await mkdir(FONT_DIR, { recursive: true });

let out = `/* Self-hosted webfonts. Generated by scripts/fetch-fonts.mjs — do not edit.\n` +
          `   Comfortaa & Nunito are SIL Open Font License 1.1. */\n\n`;
let downloaded = 0;

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?${fam.css}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${fam.name}: Google returned ${res.status}`);
  const css = await res.text();

  // Google emits one @font-face per subset, each preceded by a /* subset */ comment.
  const blocks = css.split('/*').slice(1);

  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf('*/')).trim();
    if (!KEEP_SUBSETS.includes(subset)) continue;

    const block = raw.slice(raw.indexOf('*/') + 2);
    const src = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    if (!src) continue;

    const style  = (block.match(/font-style:\s*(\w+)/) || [, 'normal'])[1];
    const weight = (block.match(/font-weight:\s*([\d\s.]+)/) || [, '400'])[1].trim();
    const range  = (block.match(/unicode-range:\s*([^;]+)/) || [, ''])[1].trim();

    const file = `${fam.name.toLowerCase()}-${subset}-${style}.woff2`;
    const bin = await fetch(src[1], { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`download failed: ${file}`);
    const buf = Buffer.from(await bin.arrayBuffer());
    await writeFile(resolve(FONT_DIR, file), buf);
    downloaded++;
    console.log(`  ✓ ${file.padEnd(34)} ${(buf.length / 1024).toFixed(1)} KB`);

    out += `@font-face {\n` +
           `  font-family: '${fam.name}';\n` +
           `  font-style: ${style};\n` +
           `  font-weight: ${weight};\n` +
           `  font-display: swap;\n` +
           `  src: url('/assets/fonts/${file}') format('woff2');\n` +
           (range ? `  unicode-range: ${range};\n` : '') +
           `}\n\n`;
  }
}

await writeFile(resolve(ROOT, 'assets/css/fonts.css'), out);
console.log(`\nWrote assets/css/fonts.css — ${downloaded} files.\n`);
